/**
 * Public board route: GET /
 */

var express = require('express');
var router = express.Router();
var { readClient } = require('../lib/supabase');
var { escHtml, GA_TAG } = require('../lib/helpers');
var { renderDateTable } = require('../lib/views');
var { filterActiveRequests, buildTestGroupSet } = require('../lib/dateFilter');
var { optionalAuth } = require('../middleware/auth');

router.get('/', optionalAuth, async function(req, res) {
    try {
        var today = new Date().toISOString().split('T')[0];
        var cutoff = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString();

        var results = await Promise.all([
            readClient.from('v3_requests').select('*')
                .eq('request_category', 'ride')
                .or('ride_plan_date.gte.' + today + ',date_fuzzy.eq.true,ride_plan_date.is.null')
                .order('created_at', { ascending: false }),
            readClient.from('monitored_groups').select('group_id, group_name, is_test').eq('active', true)
        ]);

        var allGroups = results[1].data || [];
        var testGroupFilter = buildTestGroupSet(allGroups);
        var activeCount = 0;
        for (var gi = 0; gi < allGroups.length; gi++) {
            if (!allGroups[gi].is_test) activeCount++;
        }

        var rawReqs = results[0].data || [];
        var allReqs = filterActiveRequests(rawReqs, { today: today, cutoff: cutoff, testGroups: testGroupFilter });

        // Group by date
        var byDate = {};
        for (var i = 0; i < allReqs.length; i++) {
            var key = allReqs[i].ride_plan_date || 'flexible';
            if (!byDate[key]) byDate[key] = [];
            byDate[key].push(allReqs[i]);
        }

        var sortedDates = Object.keys(byDate).sort(function(a, b) {
            if (a === 'flexible') return 1;
            if (b === 'flexible') return -1;
            return a.localeCompare(b);
        });

        var isLoggedIn = !!req.user;
        var userEmail = req.user ? req.user.email : '';

        var dateBlocksHtml;
        if (sortedDates.length === 0) {
            dateBlocksHtml = '<div class="empty">No ride activity yet.</div>';
        } else {
            var blocks = [];
            for (var di = 0; di < sortedDates.length; di++) {
                var dk = sortedDates[di];
                blocks.push(renderDateTable(dk, byDate[dk], isLoggedIn));
            }
            dateBlocksHtml = blocks.join('\n');
        }

        var totalCount = allReqs.length;
        var subtitle = 'Tracking <strong>' + totalCount + ' ride request' + (totalCount !== 1 ? 's' : '') +
                      '</strong> across <strong>' + activeCount + ' WhatsApp group' + (activeCount !== 1 ? 's' : '') +
                      '</strong> this week';

        var authHtml = isLoggedIn
            ? '<div class="auth-link"><span class="auth-email-display">' + escHtml(userEmail) + '</span> · <a href="/logout">Sign out</a></div>'
            : '<div class="auth-link"><a href="/login">Sign in with @tamu.edu</a> to see full names &amp; numbers</div>';

        var html = [
            '<!DOCTYPE html>',
            '<html lang="en">',
            '<head>',
            GA_TAG,
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<title>Aggie Connect</title>',
            '<style>',
            '  * { margin: 0; padding: 0; box-sizing: border-box; }',
            '  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #fafafa; color: #1a1a1a; line-height: 1.45; }',
            '  .container { max-width: 100%; margin: 0 auto; padding: 20px 24px; }',
            '  .hero { text-align: center; margin-bottom: 16px; }',
            '  .hero h1 { font-size: 22px; font-weight: 700; letter-spacing: -0.5px; }',
            '  .hero .subtitle { font-size: 13px; color: #666; margin-top: 2px; }',
            '  .hero .subtitle strong { color: #1a1a1a; }',
            '  .hero .tagline { font-size: 13px; color: #999; margin-top: 4px; }',
            '  .hero .tagline a { color: #500000; text-decoration: none; }',
            '  .hero .tagline a:hover { text-decoration: underline; }',
            '  .legend { display: flex; gap: 20px; align-items: center; font-size: 14px; font-weight: 600; color: #555; padding: 8px 0; margin-bottom: 8px; position: sticky; top: 0; background: #fafafa; z-index: 20; border-bottom: 1px solid #e8e8e8; justify-content: center; }',
            '  .legend-right { position: absolute; right: 0; top: 0; bottom: 0; display: flex; align-items: center; gap: 10px; }',
            '  .legend-date { position: absolute; left: 0; top: 0; bottom: 0; display: flex; align-items: center; font-size: 13px; font-weight: 700; color: #333; opacity: 0; transition: opacity 0.2s; }',
            '  .legend-date.visible { opacity: 1; }',
            '  .legend-item { display: flex; align-items: center; gap: 5px; }',
            '  .clock { font-size: 12px; font-weight: 600; color: #888; white-space: nowrap; }',
            '  .date-block { margin-bottom: 24px; }',
            '  .date-label { font-size: 14px; font-weight: 700; color: #333; padding: 6px 0 4px; border-bottom: 2px solid #e0e0e0; margin-bottom: 0; display: flex; align-items: center; gap: 8px; }',
            '  .today-badge { display: inline-block; background: #dcfce7; color: #16a34a; font-size: 10px; font-weight: 600; padding: 1px 6px; border-radius: 3px; }',
            '  .date-summary { margin-left: auto; font-size: 11px; font-weight: 400; color: #999; }',
            '  .ride-table { width: 100%; border-collapse: separate; border-spacing: 0; font-size: 13px; margin-bottom: 4px; }',
            '  .ride-table td, .ride-table th { border: 1px solid #e8e8e8; border-top: none; padding: 5px 10px; vertical-align: top; }',
            '  .ride-table tr:first-child td, .ride-table tr:first-child th { border-top: 1px solid #e8e8e8; }',
            '  .ride-table tr:hover { background: #f5f5f5; }',
            '  .col-type { width: 30px; text-align: center; font-size: 14px; }',
            '  .route-short { display: none; }',
            '  .col-name { font-weight: 600; white-space: nowrap; color: #333; }',
            '  .col-phone { white-space: nowrap; color: #888; font-size: 12px; }',
            '  .wa-link { display: inline-block; vertical-align: middle; margin-left: 4px; }',
            '  .wa-icon { width: 16px; height: 16px; vertical-align: middle; }',
            '  .col-route { white-space: nowrap; color: #555; }',
            '  .col-msg { color: #666; max-width: 320px; word-wrap: break-word; overflow-wrap: break-word; }',
            '  .col-depart { white-space: nowrap; color: #555; font-size: 12px; text-align: right; font-weight: 600; }',
            '  .col-depart .na { color: #ccc; font-weight: 400; }',
            '  .depart-mobile { display: none; }',
            '  .mobile-col-header { display: none; }',
            '  .col-time { white-space: nowrap; color: #999; font-size: 12px; text-align: right; }',
            '  .col-headers th { font-size: 11px; color: #888; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; padding: 4px 10px; background: #f5f5f0; border: 1px solid #e8e8e8; border-top: none; position: sticky; top: 60px; z-index: 8; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }',
            '  .col-headers .col-depart, .col-headers .col-time { text-align: right; }',
            '  .msg-sent { display: none; }',
            '  .section-header td { padding: 4px 10px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.3px; border: 1px solid #e8e8e8; position: sticky; top: 37px; z-index: 9; }',
            '  .section-leaving td { background: #dbeafe; color: #1d4ed8; }',
            '  .section-arriving td { background: #dcfce7; color: #16a34a; }',
            '  .section-others td { background: #f3f4f6; color: #6b7280; }',
            '  .row-leaving { background: #f0f7ff; }',
            '  .row-arriving { background: #f0fdf4; }',
            '  .row-others { background: #fafafa; }',
            '  .row-leaving:hover { background: #e0efff; }',
            '  .row-arriving:hover { background: #e0f9e8; }',
            '  .empty { padding: 40px; text-align: center; color: #aaa; font-size: 14px; }',
            '  .footer { text-align: center; padding: 16px 0; font-size: 11px; color: #ccc; border-top: 1px solid #eee; margin-top: 20px; }',
            '  .auth-link { font-size: 12px; font-weight: 600; white-space: nowrap; }',
            '  .auth-link a { color: #500000; text-decoration: none; }',
            '  .auth-link a:hover { text-decoration: underline; }',
            '  .auth-email-display { color: #888; font-weight: 400; }',
            '  .auth-banner { background: #fef3c7; border: 1px solid #f59e0b; border-radius: 6px; padding: 8px 16px; margin-bottom: 10px; font-size: 13px; color: #92400e; display: flex; align-items: center; justify-content: center; position: relative; }',
            '  .auth-banner a { color: #500000; font-weight: 700; text-decoration: underline; }',
            '  .auth-banner-close { cursor: pointer; color: #92400e; font-size: 18px; line-height: 1; opacity: 0.6; background: none; border: none; position: absolute; right: 12px; }',
            '  .auth-banner-close:hover { opacity: 1; }',
            '  @media (max-width: 700px) {',
            '    .container { padding: 8px 4px; }',
            '    .hero { display: none; }',
            '    .legend { flex-direction: row; flex-wrap: wrap; gap: 6px; padding: 6px 8px; position: sticky; top: 0; font-size: 12px; justify-content: center; }',
            '    .legend-right { position: static; display: flex; gap: 6px; }',
            '    .legend-date { display: none; }',
            '    .legend-item { font-size: 11px; }',
            '    .auth-link { font-size: 10px; }',
            '    .clock { font-size: 10px; }',
            '    .auth-banner { font-size: 11px; padding: 6px 28px 6px 8px; text-align: center; }',
            '    .date-label { font-size: 13px; font-weight: 700; }',
            '    .section-header td { position: static; font-size: 10px; padding: 3px 6px; }',
            '    .col-headers { display: none; }',
            '    .mobile-col-header { display: flex; position: sticky; top: 30px; z-index: 15; background: #f5f5f0; border-bottom: 1px solid #e8e8e8; padding: 3px 4px; font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.3px; color: #888; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }',
            '    .mobile-col-header span:nth-child(1) { width: 26px; flex-shrink: 0; }',
            '    .mobile-col-header span:nth-child(2) { flex: 1; }',
            '    .mobile-col-header span:nth-child(3) { flex: 2; }',
            '    .mobile-col-header span:nth-child(4) { width: 80px; flex-shrink: 0; text-align: right; }',
            '    .ride-table { font-size: 12px; min-width: 0; width: 100%; }',
            '    .ride-table td, .ride-table th { padding: 5px 4px; }',
            '    .col-type { width: 26px; }',
            '    .col-name { display: none; }',
            '    .col-phone { display: none; }',
            '    .col-route { white-space: normal; font-size: 11px; word-break: break-word; }',
            '    .route-full { display: inline; }',
            '    .route-short { display: none; }',
            '    .msg-sent { display: block; font-size: 9px; color: #aaa; margin-top: 2px; }',
            '    .col-msg { max-width: none; font-size: 11px; }',
            '    .col-depart { font-size: 11px; white-space: nowrap; }',
            '    .depart-full { display: none; }',
            '    .depart-mobile { display: inline; }',
            '    .col-time { display: none; }',
            '  }',
            '  .fab { position: fixed; bottom: 28px; right: 28px; width: 60px; height: 60px; border-radius: 50%; background: #500000; color: #fff; border: none; font-size: 32px; line-height: 60px; text-align: center; cursor: pointer; box-shadow: 0 4px 16px rgba(80,0,0,0.35); z-index: 1000; transition: transform 0.2s, background 0.2s; }',
            '  .fab:hover { background: #6b0000; transform: scale(1.08); }',
            '  .fab:active { background: #3a0000; transform: scale(0.96); }',
            '  .fab.open { transform: rotate(45deg); }',
            '  .fab-tooltip { display: none; position: fixed; bottom: 100px; right: 20px; background: #fff; border: 1px solid #e0e0e0; border-radius: 10px; padding: 14px 18px; box-shadow: 0 4px 20px rgba(0,0,0,0.15); z-index: 1001; font-size: 14px; color: #333; max-width: 260px; text-align: center; }',
            '  .fab-tooltip.visible { display: block; animation: fadeIn 0.2s ease-out; }',
            '  .fab-tooltip a { color: #500000; font-weight: 700; text-decoration: underline; }',
            '  .fab-tooltip .fab-tooltip-arrow { position: absolute; bottom: -8px; right: 30px; width: 0; height: 0; border-left: 8px solid transparent; border-right: 8px solid transparent; border-top: 8px solid #fff; }',
            '  .modal-overlay { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.45); z-index: 999; justify-content: center; align-items: flex-end; padding: 20px; }',
            '  .modal-overlay.active { display: flex; }',
            '  .ride-form-panel { background: #fff; border-radius: 16px 16px 0 0; width: 100%; max-width: 480px; max-height: 85vh; overflow-y: auto; padding: 24px 20px 20px; box-shadow: 0 -4px 24px rgba(0,0,0,0.15); animation: slideUp 0.25s ease-out; }',
            '  @keyframes slideUp { from { transform: translateY(40px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }',
            '  @keyframes fadeIn { from { opacity: 0; transform: translateY(4px); } to { opacity: 1; transform: translateY(0); } }',
            '  .ride-form-panel h2 { font-size: 18px; font-weight: 700; margin-bottom: 16px; color: #1a1a1a; }',
            '  .form-group { margin-bottom: 14px; }',
            '  .form-label { display: block; font-size: 13px; font-weight: 600; color: #555; margin-bottom: 4px; }',
            '  .form-input, .form-select, .form-textarea { width: 100%; padding: 10px 12px; font-size: 15px; border: 1px solid #d0d0d0; border-radius: 8px; outline: none; transition: border-color 0.2s; font-family: inherit; background: #fff; }',
            '  .form-input:focus, .form-select:focus, .form-textarea:focus { border-color: #500000; }',
            '  .form-textarea { resize: vertical; min-height: 60px; }',
            '  .type-toggle { display: flex; border: 2px solid #500000; border-radius: 8px; overflow: hidden; }',
            '  .type-toggle label { flex: 1; text-align: center; padding: 10px; font-size: 14px; font-weight: 600; cursor: pointer; transition: background 0.2s, color 0.2s; color: #500000; background: #fff; }',
            '  .type-toggle input { display: none; }',
            '  .type-toggle input:checked + label { background: #500000; color: #fff; }',
            '  .other-input { display: none; margin-top: 6px; }',
            '  .other-input.visible { display: block; }',
            '  .form-submit { width: 100%; padding: 12px; font-size: 15px; font-weight: 600; background: #500000; color: #fff; border: none; border-radius: 8px; cursor: pointer; margin-top: 8px; transition: background 0.2s; }',
            '  .form-submit:hover { background: #6b0000; }',
            '  .form-submit:disabled { background: #999; cursor: not-allowed; }',
            '  .form-msg { padding: 10px 14px; border-radius: 8px; font-size: 13px; margin-bottom: 12px; display: none; }',
            '  .form-msg.error { display: block; background: #fef2f2; color: #b91c1c; border: 1px solid #fecaca; }',
            '  .form-msg.success { display: block; background: #f0fdf4; color: #16a34a; border: 1px solid #bbf7d0; }',
            '  .form-error { border-color: #ef4444 !important; background: #fef2f2 !important; }',
            '  @media (max-width: 700px) {',
            '    .fab { bottom: 20px; right: 20px; width: 54px; height: 54px; font-size: 28px; line-height: 54px; }',
            '    .fab-tooltip { bottom: 86px; right: 12px; }',
            '    .modal-overlay { padding: 0; }',
            '    .ride-form-panel { max-height: 90vh; padding: 20px 16px 16px; }',
            '  }',
            '</style>',
            '</head>',
            '<body>',
            '<div class="container">',
            '  <div class="hero">',
            '    <h1>Aggie Connect</h1>',
            '    <p class="subtitle">' + subtitle + '</p>',
            '    <p class="tagline">Find someone going your way. Updated in real time from WhatsApp groups. <a href="/faq">FAQs &mdash; how, why, what?</a></p>',
            '  </div>',
            '  <div class="legend">',
            '    <div class="legend-date" id="sticky-date"></div>',
            '    <div class="legend-item">\u270B Looking for ride</div>',
            '    <div class="legend-item">\uD83D\uDE97 Offering ride</div>',
            '    <div class="legend-right">',
            authHtml,
            '      <div class="clock"><span id="live-time"></span> CT</div>',
            '    </div>',
            '  </div>',
            isLoggedIn ? '' : '  <div class="auth-banner" id="auth-banner"><span>\uD83D\uDD12 Names and phone numbers are redacted. &nbsp;<a href="/login">Sign in with your @tamu.edu email</a>&nbsp; to see full contact details.</span><button class="auth-banner-close" onclick="document.getElementById(\'auth-banner\').style.display=\'none\'">&times;</button></div>',
            '  <div class="mobile-col-header"><span></span><span>Route</span><span>Message</span><span>Departs</span></div>',
            dateBlocksHtml,
            '  <div class="footer">' + totalCount + ' total requests &middot; ' + activeCount + ' groups monitored &middot; <a href="/faq">FAQ</a> &middot; <a href="/terms">Terms</a> &middot; v3.2</div>',
            '</div>',
            '',
            '<!-- FAB -->',
            '<button class="fab" id="ride-fab" title="Post a ride" aria-label="Post a ride">+</button>',
            '',
            '<!-- Sign-in tooltip (unauthenticated) -->',
            '<div class="fab-tooltip" id="fab-tooltip">',
            '  <a href="/login">Sign in with @tamu.edu</a> to offer or post a ride',
            '  <div class="fab-tooltip-arrow"></div>',
            '</div>',
            '',
            '<!-- Ride form modal (authenticated) -->',
            '<div class="modal-overlay" id="ride-modal">',
            '  <div class="ride-form-panel">',
            '    <h2>Post a Ride</h2>',
            '    <div class="form-msg" id="form-msg"></div>',
            '    <form id="ride-form" autocomplete="off">',
            '      <div class="form-group">',
            '        <div class="form-label">I am... <span style="color:#ef4444">*</span></div>',
            '        <div class="type-toggle">',
            '          <input type="radio" name="type" id="type-need" value="need">',
            '          <label for="type-need">\u270B Looking for a ride</label>',
            '          <input type="radio" name="type" id="type-offer" value="offer">',
            '          <label for="type-offer">\uD83D\uDE97 Offering a ride</label>',
            '        </div>',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="origin">From <span style="color:#ef4444">*</span></label>',
            '        <select class="form-select" id="origin" name="origin">',
            '          <option value="">Select origin...</option>',
            '          <option value="College Station">College Station</option>',
            '          <option value="Houston">Houston</option>',
            '          <option value="Houston IAH">Houston IAH</option>',
            '          <option value="Houston Hobby">Houston Hobby</option>',
            '          <option value="Dallas">Dallas</option>',
            '          <option value="Dallas DFW">Dallas DFW</option>',
            '          <option value="Fort Worth">Fort Worth</option>',
            '          <option value="Austin">Austin</option>',
            '          <option value="Austin Airport">Austin Airport</option>',
            '          <option value="San Antonio">San Antonio</option>',
            '          <option value="Other">Other</option>',
            '        </select>',
            '        <input class="form-input other-input" id="origin-other" name="originOther" placeholder="Enter city/location" maxlength="100">',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="destination">To <span style="color:#ef4444">*</span></label>',
            '        <select class="form-select" id="destination" name="destination">',
            '          <option value="">Select destination...</option>',
            '          <option value="College Station">College Station</option>',
            '          <option value="Houston">Houston</option>',
            '          <option value="Houston IAH">Houston IAH</option>',
            '          <option value="Houston Hobby">Houston Hobby</option>',
            '          <option value="Dallas">Dallas</option>',
            '          <option value="Dallas DFW">Dallas DFW</option>',
            '          <option value="Fort Worth">Fort Worth</option>',
            '          <option value="Austin">Austin</option>',
            '          <option value="Austin Airport">Austin Airport</option>',
            '          <option value="San Antonio">San Antonio</option>',
            '          <option value="Other">Other</option>',
            '        </select>',
            '        <input class="form-input other-input" id="dest-other" name="destOther" placeholder="Enter city/location" maxlength="100">',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="ride-date">Date <span style="color:#ef4444">*</span></label>',
            '        <input class="form-input" type="date" id="ride-date" name="date" required>',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="ride-name">Name <span style="color:#ef4444">*</span></label>',
            '        <input class="form-input" type="text" id="ride-name" name="name" placeholder="Your name" required maxlength="100">',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="ride-phone">Phone Number <span style="color:#ef4444">*</span></label>',
            '        <input class="form-input" type="tel" id="ride-phone" name="phone" placeholder="(XXX) XXX-XXXX" required maxlength="20">',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="ride-time">Preferred Time <span style="color:#999;font-weight:400">(optional)</span></label>',
            '        <input class="form-input" type="time" id="ride-time" name="time">',
            '      </div>',
            '      <div class="form-group">',
            '        <label class="form-label" for="ride-comments">Comments <span style="color:#999;font-weight:400">(seats, charge, etc.)</span></label>',
            '        <textarea class="form-textarea" id="ride-comments" name="comments" placeholder="e.g. 2 seats available, splitting gas" maxlength="500"></textarea>',
            '      </div>',
            '      <button class="form-submit" type="submit" id="form-submit-btn">Submit</button>',
            '    </form>',
            '  </div>',
            '</div>',
            '',
            '<script>',
            '(function() {',
            '  function updateClock() {',
            '    var now = new Date();',
            '    var opts = { hour: "numeric", minute: "2-digit", hour12: true, timeZone: "America/Chicago" };',
            '    var el = document.getElementById("live-time");',
            '    if (el) el.textContent = now.toLocaleTimeString("en-US", opts);',
            '  }',
            '  updateClock();',
            '  setInterval(updateClock, 30000);',
            '',
            '  var stickyEl = document.getElementById("sticky-date");',
            '  var dateBlocks = document.querySelectorAll(".date-block");',
            '  if (stickyEl && dateBlocks.length) {',
            '    var legend = document.querySelector(".legend");',
            '    function updateStickyDate() {',
            '      var legendBottom = legend.getBoundingClientRect().bottom;',
            '      var current = null;',
            '      for (var i = 0; i < dateBlocks.length; i++) {',
            '        var rect = dateBlocks[i].getBoundingClientRect();',
            '        if (rect.top < legendBottom + 10 && rect.bottom > legendBottom) {',
            '          var label = dateBlocks[i].querySelector(".date-label");',
            '          if (label && label.getBoundingClientRect().top < legendBottom) {',
            '            var dt = label.querySelector(".date-text");',
            '            var sm = label.querySelector(".date-summary");',
            '            current = (dt ? dt.textContent.trim() : label.textContent.trim().split("\\n")[0]) + (sm ? " \\u00B7 " + sm.textContent.trim() : "");',
            '          }',
            '        }',
            '      }',
            '      if (current) {',
            '        stickyEl.textContent = current;',
            '        stickyEl.classList.add("visible");',
            '      } else {',
            '        stickyEl.classList.remove("visible");',
            '      }',
            '    }',
            '    window.addEventListener("scroll", updateStickyDate, { passive: true });',
            '  }',
            '',
            '  document.addEventListener("click", function(e) {',
            '    var td = e.target.closest ? e.target.closest(".col-msg") : null;',
            '    if (td && window.innerWidth <= 700) td.classList.toggle("expanded");',
            '  });',
            '',
            '  window.logWaClick = function(route, type, date) {',
            '    gtag("event","wa_click",{route:route,type:type,date:date});',
            '    fetch("/log-click",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({route:route,type:type,date:date})}).catch(function(){});',
            '  }',
            '',
            '  var isLoggedIn = !!document.querySelector(".auth-email-display");',
            '  var fab = document.getElementById("ride-fab");',
            '  var tooltip = document.getElementById("fab-tooltip");',
            '  var modal = document.getElementById("ride-modal");',
            '  var form = document.getElementById("ride-form");',
            '  var msgEl = document.getElementById("form-msg");',
            '  var submitBtn = document.getElementById("form-submit-btn");',
            '',
            '  var dateInput = document.getElementById("ride-date");',
            '  if (dateInput) {',
            '    var d = new Date();',
            '    var todayStr = d.getFullYear() + "-" + String(d.getMonth()+1).padStart(2,"0") + "-" + String(d.getDate()).padStart(2,"0");',
            '    dateInput.setAttribute("min", todayStr);',
            '    dateInput.value = todayStr;',
            '  }',
            '',
            '  fab.addEventListener("click", function() {',
            '    if (!isLoggedIn) {',
            '      var vis = tooltip.classList.contains("visible");',
            '      tooltip.classList.toggle("visible", !vis);',
            '      return;',
            '    }',
            '    var isOpen = modal.classList.contains("active");',
            '    if (isOpen) {',
            '      modal.classList.remove("active");',
            '      fab.classList.remove("open");',
            '    } else {',
            '      tooltip.classList.remove("visible");',
            '      modal.classList.add("active");',
            '      fab.classList.add("open");',
            '      msgEl.className = "form-msg";',
            '      msgEl.textContent = "";',
            '    }',
            '  });',
            '',
            '  modal.addEventListener("click", function(e) {',
            '    if (e.target === modal) {',
            '      modal.classList.remove("active");',
            '      fab.classList.remove("open");',
            '    }',
            '  });',
            '',
            '  document.addEventListener("keydown", function(e) {',
            '    if (e.key === "Escape") {',
            '      modal.classList.remove("active");',
            '      fab.classList.remove("open");',
            '      tooltip.classList.remove("visible");',
            '    }',
            '  });',
            '',
            '  document.addEventListener("click", function(e) {',
            '    if (!fab.contains(e.target) && !tooltip.contains(e.target)) {',
            '      tooltip.classList.remove("visible");',
            '    }',
            '  });',
            '',
            '  document.getElementById("origin").addEventListener("change", function() {',
            '    var oi = document.getElementById("origin-other");',
            '    if (this.value === "Other") { oi.classList.add("visible"); oi.focus(); }',
            '    else { oi.classList.remove("visible"); oi.value = ""; }',
            '  });',
            '  document.getElementById("destination").addEventListener("change", function() {',
            '    var di = document.getElementById("dest-other");',
            '    if (this.value === "Other") { di.classList.add("visible"); di.focus(); }',
            '    else { di.classList.remove("visible"); di.value = ""; }',
            '  });',
            '',
            '  form.addEventListener("submit", async function(e) {',
            '    e.preventDefault();',
            '    msgEl.className = "form-msg";',
            '    msgEl.textContent = "";',
            '    submitBtn.disabled = true;',
            '    submitBtn.textContent = "Submitting...";',
            '',
            '    var fieldMap = { type: ".type-toggle", origin: "#origin", destination: "#destination", date: "#ride-date", name: "#ride-name", phone: "#ride-phone" };',
            '    Object.values(fieldMap).forEach(function(sel) {',
            '      var el = document.querySelector(sel);',
            '      if (el) el.classList.remove("form-error");',
            '    });',
            '',
            '    function showError(msg, fields) {',
            '      msgEl.className = "form-msg error";',
            '      msgEl.textContent = msg;',
            '      if (fields && fields.length) {',
            '        fields.forEach(function(f) {',
            '          var el = document.querySelector(fieldMap[f]);',
            '          if (el) el.classList.add("form-error");',
            '        });',
            '      }',
            '      document.querySelector(".ride-form-panel").scrollTo({ top: 0, behavior: "smooth" });',
            '      submitBtn.disabled = false;',
            '      submitBtn.textContent = "Submit";',
            '    }',
            '',
            '    var typeEl = form.querySelector(\'input[name="type"]:checked\');',
            '    if (!typeEl) {',
            '      showError("Please select Looking or Offering.", ["type"]);',
            '      return;',
            '    }',
            '',
            '    var body = {',
            '      type: typeEl.value,',
            '      origin: form.querySelector("#origin").value,',
            '      destination: form.querySelector("#destination").value,',
            '      date: form.querySelector("#ride-date").value,',
            '      name: form.querySelector("#ride-name").value.trim(),',
            '      phone: form.querySelector("#ride-phone").value.trim(),',
            '      time: form.querySelector("#ride-time").value || "",',
            '      comments: form.querySelector("#ride-comments").value.trim(),',
            '      originOther: (form.querySelector("#origin-other").value || "").trim(),',
            '      destOther: (form.querySelector("#dest-other").value || "").trim()',
            '    };',
            '',
            '    try {',
            '      var resp = await fetch("/submit", {',
            '        method: "POST",',
            '        headers: { "Content-Type": "application/json" },',
            '        body: JSON.stringify(body)',
            '      });',
            '      var data = await resp.json();',
            '',
            '      if (!resp.ok) {',
            '        if (resp.status === 401) { window.location.href = "/login"; return; }',
            '        showError(data.error || "Something went wrong.", data.fields || []);',
            '        return;',
            '      }',
            '',
            '      msgEl.className = "form-msg success";',
            '      var matchMsg = data.matches > 0 ? " We found " + data.matches + " potential match(es)!" : "";',
            '      msgEl.textContent = "Ride posted successfully!" + matchMsg;',
            '      submitBtn.textContent = "Done!";',
            '      document.querySelector(".ride-form-panel").scrollTo({ top: 0, behavior: "smooth" });',
            '      setTimeout(function() {',
            '        modal.classList.remove("active");',
            '        fab.classList.remove("open");',
            '        window.location.reload();',
            '      }, 2000);',
            '    } catch (err) {',
            '      showError("Network error. Please try again.", []);',
            '    }',
            '  });',
            '})()',
            '</script>',
            '</body>',
            '</html>'
        ].join('\n');

        res.send(html);
    } catch (err) {
        console.error('[Dashboard] Error:', err.message);
        res.status(500).send('Error loading dashboard');
    }
});

module.exports = router;
